# baseURL = "https://www.thebetterplay.com"
baseURL = "/"
language = "de"
languageCode = "de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
title = "The Better Play"
theme = "custom"

# FOOTER
# Footer about
[[menu.footer]]
  name = "About"
  identifier = "about"
  url = "/company/about-us"
  weight = 1
[[Languages.de.menu.footer]]
  name = "Über uns"
  identifier = "about"
  url = "/company/ueber-uns"
  weight = 1
# Footer imprint
[[menu.footer]]
  name = "Imprint"
  identifier = "imprint"
  url = "/company/imprint"
  weight = 2
[[Languages.de.menu.footer]]
  name = "Impressum"
  identifier = "imprint"
  url = "/company/impressum"
  weight = 2
# Footer privacy-policy
[[menu.footer]]
  name = "Privacy Policy"
  identifier = "privacy-policy"
  url = "/company/privacy-policy"
  weight = 3
[[Languages.de.menu.footer]]
  name = "Datenschutzerklärung"
  identifier = "privacy-policy"
  url = "/company/datenschutzerklärung"
  weight = 3
# Footer affiliate
[[menu.footer]]
  name = "Affiliate Disclaimer"
  identifier = "affiliate-disclaimer"
  url = "/company/affiliate-disclaimer"
  weight = 4
[[Languages.de.menu.footer]]
  name = "Amazon Partnerprogramm"
  identifier = "affiliate-disclaimer"
  url = "/company/amazon-partnerprogramm"
  weight = 4
# Footer contact
[[menu.footer]]
  name = "Contact"
  identifier = "contact"
  url = "/contact"
  weight = 5
[[Languages.de.menu.footer]]
  name = "Kontakt"
  identifier = "contact"
  url = "/contact"
  weight = 5

[Languages]
[Languages.de]
weight = 1
title = "The Better Play"
languageName = "Deutsch"
[Languages.en]
weight = 2
title = "The Better Play"
languageName = "English"
